### ISSUE TITLE
Use correct terminology 

### ISSUE THREAD

**Issue by NeuroShepherd** [lmu-osc/Introduction-Simulations-in-R#16]
1. Whenever the word “replicate” is used (e.g., in purpose.qmd), replace the instance with “repeat” or “repetition” (depending on the context; you may need to adjust the wording beyond replacing the word in some cases to make it work grammatically).
2. Whenever the word “simulation” (or “simulations”) is used to mean repetition(s) (e.g., in the image captions in check-alpha.qmd), replace the instance with “simulation repetition” (or ”simulation repetitions”).
3. If you see any instances of “nrep” where it would be useful to change the wording around it to include the word “repetitions”, feel free to make those changes as well.

**Comment by NeuroShepherd** [comment]
Being addressed in #17

**Comment by langejulian** [comment]
- I decided to shorten "simulation repetitions" to "repetitions" in most contexts but especially when used in combination with "number of", because it seems redundant (we don't say "simulation sample size" either) and less common to me.
- I added "replications" once as a common alternative term (agreed to do that with Malika but forgot to mention it in my mail).
